//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SignupL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "first Name is Requre")]
        public string firstName { get; set; }
        [Required(ErrorMessage = "Last Name is Requre")]
        public string lastName { get; set; }
        [Required(ErrorMessage = "Gender is Requre")]
        public string gender { get; set; }
        [Required(ErrorMessage = "Age is Requre")]
        public int age { get; set; }
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string email { get; set; }
        [Required(ErrorMessage = "Username is Requre")]
        public string username { get; set; }
        [Required(ErrorMessage = "Password is Requre")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required(ErrorMessage = "Confirm password is Requre")]
        [DataType(DataType.Password)]
        [Compare("password",ErrorMessage ="Password is not match")]
        public string Confirm_password { get; set; }
    }
}
